steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pathway-edu-backend-ms1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pathway-edu-backend-ms1']
images:
  - 'gcr.io/$PROJECT_ID/pathway-edu-backend-ms1'
